### ISSUE TITLE
Is the compatibility tool confused about whether $type is supported?

### ISSUE THREAD

**Issue by snoblenet** [awslabs/amazon-documentdb-tools#18]
According to [the DocumentDB documentation](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html), `$type` is supported.

However, when I run the compability tool against my MongoDB log, it reports that using `$type` is an error.

I believe this is because the compatibility tool's `dollar.csv` file lists `$type` twice: once as 'yes' for 3.6 and 4.4, and once as 'no' for 3.6 and 4.4.

**Comment by tmcallaghan** [comment]
Good catch. I've removed the incorrect $type line as well as about two commands that were in the file twice. Sorted the non-header lines for easier research and editing going forward.
