### ISSUE TITLE
Script ignores index_names and causes errors

### ISSUE THREAD

**Issue by RTodorov** [awslabs/amazon-documentdb-tools#2]
Hello there,

Tried using the script to import indexes from a Mongo cluster to DocumentDB but seems like, when re-creating the indexes, the script doesn't try to use the original index name. This is a problem because, if we have too many fields, we'll fall into the `namespace name generated from index name is too long` problem.

My workaround for it was to manually add this:

`index_options['name'] = index_name`

before the `collection.create_index` call on https://github.com/awslabs/amazon-documentdb-tools/blob/master/migrationtools/documentdb_index_tool.py#L481.

Any reason why you're not passing the original index name from the dump?

Thank you

**Comment by brianmhess** [comment]
I addressed this with this commit: https://github.com/awslabs/amazon-documentdb-tools/commit/6c7c4dd8f7521cc5c26dd6c2ceb6b7085598a645
