### ISSUE TITLE
--show-issues requires --auth-db argument

### ISSUE THREAD

**Issue by bertrandmartel** [awslabs/amazon-documentdb-tools#4]
From [this tutorial](https://aws.amazon.com/fr/blogs/database/migrate-from-mongodb-to-amazon-documentdb-using-the-offline-method/) using :

```bash
python amazon-documentdb-tools/migrationtools/documentdb_index_tool.py \
        --show-issues --dir dump
```
I've got:

> documentdb_index_tool.py: error: --auth-db requires both --username and --password.

Adding some fake --auth-db --username and --password fix it : 

```bash
python amazon-documentdb-tools/migrationtools/documentdb_index_tool.py \
      --show-issues --dir dump --auth-db 'test' --username 'test' --password 'test'
```
but shouldn't it work without those arguments ?

**Comment by brianmhess** [comment]
I believe I have fixed this with this commit: https://github.com/awslabs/amazon-documentdb-tools/commit/6c7c4dd8f7521cc5c26dd6c2ceb6b7085598a645
