### ISSUE TITLE
which your last change there is no way to provide auth information to access the db

### ISSUE THREAD

**Issue by goxlarge** [awslabs/amazon-documentdb-tools#52]
why???? 
usage: documentdb_index_tool.py [-h] [--debug] [--dry-run] --uri URI --dir DIR
                                [--show-compatible] [--show-issues]
                                [--dump-indexes] [--restore-indexes]
                                [--skip-incompatible] [--support-2dsphere]
                                [--skip-python-version-check]

**Comment by tmcallaghan** [comment]
Auth is provided via URI. The reason I switched to URI is to greatly simplify the code and number of arguments.
