### ISSUE TITLE
from bson.json_util import dumps

### ISSUE THREAD

**Issue by TirushV** [awslabs/amazon-documentdb-tools#53]
from bson.json_util import dumps
No module named bson.json_util when running the dump indexes command 
![Screenshot 2023-01-28 at 9 22 26 AM](https://user-images.githubusercontent.com/84138572/215240812-49e1622a-04b3-49e4-8a61-ce365971406e.png)

**Comment by TirushV** [comment]
Looks like support for documentdb removed. Because theres no option for pem file using by DocumentDB in this tool

**Comment by tmcallaghan** [comment]
> Looks like support for documentdb removed. Because theres no option for pem file using by DocumentDB in this tool

DocumentDB is absolutely supported. You need to provide the pem file as part of the URI. Full documentation is available at https://www.mongodb.com/docs/manual/reference/connection-string/. Keep in mind that using SSL or TLS is dependent on the version of PyMongo you are using.

**Comment by howmun** [comment]
I encountered this error in Amazon Linux 2 , turns out the default python is python2, so just need to run the commands with python3, e.g.:

```
python3 migrationtools/documentdb_index_tool.py --dump-indexes
--uri mongodb://sample-user:user-password@sample-source-cluster.node.us-east 1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'
--dir ~/index.js/ 
```

**Comment by tmcallaghan** [comment]
Nothing to do here.
