### ISSUE TITLE
Getting an error: bash: --dir: command not found.

### ISSUE THREAD

**Issue by hassanaly-sage** [awslabs/amazon-documentdb-tools#55]
I have been trying to dump indexes using this command:
`python3 migrationtools/documentdb_index_tool.py --dump-indexes --uri mongodb://<UserName:Password>@<My-DocumentDB-cluster-endpoint>/?ssl=true&tlsCAFile=rds-combined-ca-bundle.pem --dir ./my-dir/`

But I keep getting this error: --dir: command not found.

Could you please add an example for a connection command for a DocumentDB cluster/instance in the readme, I think that will help a lot.

Thank you.

**Comment by mihaialdoiu** [comment]
Try --uri like this: `--uri "mongodb://user:password@mydocdb.cluster-cdtjj00yfi95.eu-west-2.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=rds-combined-ca-bundle.pem&replicaSet=rs0&retryWrites=false"`. The uri should be quoted.

**Comment by hassanaly-sage** [comment]
Thanks, that worked for me.
