### ISSUE TITLE
Question - is there an equivalent to the DocumentDB Compatibility Tool that would work with Mongoengine?

### ISSUE THREAD

**Issue by codekiln** [awslabs/amazon-documentdb-tools#82]
As far as I can see, `compat.py` looks for certain mongo keywords directly in the lines of the python files or mongo log files. I have doubts about whether this technique would work with abstraction layers on top of pymongo such as Mongoengine. Is there any equivalent tool that would work with the Mongoengine python library?

**Comment by tmcallaghan** [comment]
Users can run the compatibility tool in two modes - 1/ code scanning or 2/ log scanning. For languages or implementations that do not include the actual $ operators themselves you can use the log scanning technique. You'll need to put your MongoDB server into profiling where it logs all operations for a period of time then scan the logs.
