### ISSUE TITLE
global-clusters-automation: add support for Performance Insights & I/O-optimized

### ISSUE THREAD

**Issue by dbonser** [awslabs/amazon-documentdb-tools#94]
Chnage add_secondaryCluster.py and failover_and_convert_to_global.py to support configuring I/O-Optimized and Performance Insights settings.

I/O-Optimized can be specified when creating the secondary cluster.
Performance Insights can only be enabled after the secondary cluster instances have been created.

**Comment by gottumuk** [comment]
@dbonser @tmcallaghan Do we also need to enable PI and change the Storage type to the failed over cluster (new primry) or just the new secondary cluster.

**Comment by dbonser** [comment]
@tmcallaghan I tested all scenarios against @gottumuk's changes and it looks good. Ready to merge.
