### ISSUE TITLE
How to exclude _id_ index in output of dump-indexes

### ISSUE THREAD

**Issue by dataTrevor** [awslabs/amazon-documentdb-tools#98]
If I want to migrate indexes from mongoDB to DocDB elastic Cluster, _id should be created in DocDB before restore indexes, and there would be a  index {"_id": "hashed"} created in DocDB elastic Cluster. If we don't remove the "_id_" from the dumped indexes file(when --dump-indexes), the documentdb-index-tool can't restore the indexes to the collection in  DocDB elastic Cluster.  Errors like following:  'errmsg': "a collection 'ycsb.test' already exists"

**Comment by tmcallaghan** [comment]
Added command line option --skip-id-indexes in commit f621c43
